name: docker

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0"

concurrency:
  group: docker
  cancel-in-progress: true

jobs:
  docker:
    strategy:
      fail-fast: false
      matrix:
        base-image-tag:
          - bookworm
          - bullseye
          - buster
          - jammy
          - focal
          - bionic
          - xenial
        gcc-version:
          - "13.2.0"
          - "12.3.0"
          - "11.4.0"
          - "10.5.0"
          - "9.5.0"
    env:
      DOCKERHUB_REPOSITORY: zhongruoyu/gcc-ports
      PLATFORMS: linux/amd64
      BINUTILS_VERSION: "2.42"
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variables
        run: |
          cat <<EOF | tee -a "$GITHUB_ENV"
          BASE_IMAGE_TAG=${{ matrix.base-image-tag }}
          GCC_VERSION=${{ matrix.gcc-version }}
          GCC_VERSION_MAJOR=$(echo "${{ matrix.gcc-version }}" | cut -d '.' -f 1)
          GCC_VERSION_MINOR=$(echo "${{ matrix.gcc-version }}" | cut -d '.' -f 2)
          GCC_VERSION_REVISION=$(echo "${{ matrix.gcc-version }}" | cut -d '.' -f 3)
          EOF
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          tags: |
            ${{ env.DOCKERHUB_REPOSITORY }}:${{ env.GCC_VERSION_MAJOR }}-${{ env.BASE_IMAGE_TAG }}
            ${{ env.DOCKERHUB_REPOSITORY }}:${{ env.GCC_VERSION_MAJOR }}.${{ env.GCC_VERSION_MINOR }}-${{ env.BASE_IMAGE_TAG }}
            ${{ env.DOCKERHUB_REPOSITORY }}:${{ env.GCC_VERSION_MAJOR }}.${{ env.GCC_VERSION_MINOR }}.${{ env.GCC_VERSION_REVISION }}-${{ env.BASE_IMAGE_TAG }}
          platforms: ${{ env.PLATFORMS }}
          build-args: |
            BASE_IMAGE_TAG=${{ env.BASE_IMAGE_TAG }}
            BINUTILS_VERSION=${{ env.BINUTILS_VERSION }}
            GCC_VERSION=${{ env.GCC_VERSION }}
          push: true
